# Formation Python  Juin 2016


## Amaury Fournier
## Velvet Consulting

## Généralités du langage

In [2]:
import numpy as np
import pandas as pd
import math

In [ ]:
#la fonction help qui peut vous renseigner si vous cherchez une information 
#typiquement je cherche la liste des mots réservés (keywords) en python grâce à la fonction help
help()

In [ ]:
#opération mathématiques (parce que python peut aussi vous servir de calculatrice !)
1+1

In [3]:
print 1+4
print 1 - 4      #les espaces sont optionnels
print 5+6*3      #comment python gère t'il les opérateurs mathématiques
print (5+6)*3
print 7/2        #Attention !

5
-3
23
33
3


In [ ]:
print 7/2.0     #présence d'un flottant
print 7//2.0    #division entière
print 7%2.      #reste
print 5e-3
print 5*10**3

In [ ]:
a = 5


In [ ]:
pygmentize -f -o formation.rtf Formation Python.py

In [ ]:
"""salut ceci est un docstring"""

In [ ]:
hauteur = 15
largeur = 26
aire = hauteur * largeur
aire

In [ ]:
haut  #toujours définir ses variables avant de les appeler

In [ ]:
"Hello, World !"

In [ ]:
'Hello, world !'

In [ ]:
hello = 'Hello world'
hello

In [ ]:
hello[0]

In [ ]:
bonjour = "Hello" + ',' + "World !"
bonjour

In [ ]:
bonjour = ""

In [ ]:
bonjour

In [ ]:
#solution 
a = input("Valeur de a :")
b = input("Valeur de b :")
c = (a**2 - b**(1/2.))
print "a² - √b : ",c 
print 'type :',type(c)

In [ ]:
a = 3
a +=1
b,c = 5,7
print 'a :',a,'\nb :',b,'\nc :',c

In [ ]:
a = 1
print "a vaut ", a ,'salut',b


In [ ]:
ma_liste = []   #initialisation d'une liste vide
nb_premiers = [2,3,5,7,11]  #liste de 5 élements int
l_mixte = ["hello",1, [3],(3,2)]

print "ma liste", ma_liste,type(ma_liste)
print "nb_premiers", nb_premiers ,type(nb_premiers)
print "l_mixte", l_mixte ,type(l_mixte), '\n'

for i in l_mixte :
    print i, type(i)


In [ ]:
print nb_premiers, ", liste de taille :", len(l_mixte)

In [ ]:
print nb_premiers

In [ ]:
nb_premiers = [2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59, 61, 67, 71, 73, 79, 83, 89]
start = 2  #inclus
stop = 15  #exclu
pas = 2
print nb_premiers
print 'start', nb_premiers[start]
print 'stop', nb_premiers[stop]
print nb_premiers[start:stop]
print nb_premiers[start:stop:pas]

In [ ]:
nb_premiers[-1:4:-1]

In [ ]:
nb_premiers[15:]

In [ ]:
nb_premiers[:10], len(nb_premiers[:10])

In [ ]:
#entier positif de zéro à 10
#phrase j'aime les pommes
#concaténnez chacun des elements de la phrase à la liste
#affichez le douzième élément de la liste
#retirez le dernier élément de la liste
#insérez l'élément 17 en deuxième position
#affichez
#triez et afficher à nouveau
#afficher l'avant dernier élément
#pour finir afficher la liste des éléments du dernier au premier (inclus) avec un pas de 3

l = range(11)
phrase = "j'aime les pommes"
l.extend(phrase)
print l[11]
l.pop()
l.insert(1,17)
print l
l.sort()
print l
print l[-2]
print(l[::-3])

In [ ]:
a = l.index(17)
b = l.index('m')
l[a], l[b] = l[b], l[a]
l

In [ ]:
print list(enumerate(l))

In [ ]:
a=3
if a > 0 :
    print ("a est strictement supérieur à 0")

In [ ]:
b=5
c = 0
if a < b and c== 0:
    print "a est strictement inférieur à b"

elif a > b:
    print "b est strictement inférieur à a"
else:
    print "b est égal à a"

In [ ]:
a=3
b=5
condition1 = a < b
condition2 = a > b
condition3 = a < 10
condition4 = a > 10

if condition1, condition3, a == 3 :
    print "a est strictement inférieur à b et a est inférieur à 10 "
if condition2  or condition4 :
    print "b est strictement inférieur à ou a est supérieur à 10"


In [ ]:
annee = input("annee : ")
if (not annee%4 and annee%100) or not anne%400 :
    print "l'année",annee,"est bissextile"
else :
    print "l'année",annee,"n'est pas bissextile"

In [ ]:
if (not 4%4 and i%100):
    print "salkut"

In [ ]:
annee_bis=[]
liste_annee = ...
for i in liste_annee:
    if ... :
        ...
annee_bis

In [ ]:
"Hello"+"World"+str(2)


In [53]:
for i in range(4,11) :
    if not i%5 and i>0:
        print "condition respectée, i =",i
        continue
    print i

4
condition respectée, i = 5
6
7
8
9
condition respectée, i = 10


In [44]:
ma_liste = range(-1,9,2) 
ma_liste

[-1, 1, 3, 5, 7]

In [45]:
l_mixte = ["hello",1, [3],(3,2)]
l_mixte

['hello', 1, [3], (3, 2)]

In [16]:
liste_ij = []
for i in range(11):
    for j in range(i):
        liste_ij.append((i,j))       
liste_ij

[(1, 0), (2, 0), (2, 1), (3, 0), (3, 1), (3, 2), (4, 0), (4, 1), (4, 2), (4, 3), (5, 0), (5, 1), (5, 2), (5, 3), (5, 4), (6, 0), (6, 1), (6, 2), (6, 3), (6, 4), (6, 5), (7, 0), (7, 1), (7, 2), (7, 3), (7, 4), (7, 5), (7, 6), (8, 0), (8, 1), (8, 2), (8, 3), (8, 4), (8, 5), (8, 6), (8, 7), (9, 0), (9, 1), (9, 2), (9, 3), (9, 4), (9, 5), (9, 6), (9, 7), (9, 8), (10, 0), (10, 1), (10, 2), (10, 3), (10, 4), (10, 5), (10, 6), (10, 7), (10, 8), (10, 9)]

In [30]:
for i in range(1,200):
    chaine =''
    if not i%3 :
        chaine+="Fizz"
    if not i%5 : 
        chaine+="Buzz"
    if i%5 and i%3 :
        chaine = str(i)
    print chaine

1
2
Fizz
4
Buzz
Fizz
7
8
Fizz
Buzz
11
Fizz
13
14
FizzBuzz
16
17
Fizz
19
Buzz
Fizz
22
23
Fizz
Buzz
26
Fizz
28
29
FizzBuzz
31
32
Fizz
34
Buzz
Fizz
37
38
Fizz
Buzz
41
Fizz
43
44
FizzBuzz
46
47
Fizz
49
Buzz
Fizz
52
53
Fizz
Buzz
56
Fizz
58
59
FizzBuzz
61
62
Fizz
64
Buzz
Fizz
67
68
Fizz
Buzz
71
Fizz
73
74
FizzBuzz
76
77
Fizz
79
Buzz
Fizz
82
83
Fizz
Buzz
86
Fizz
88
89
FizzBuzz
91
92
Fizz
94
Buzz
Fizz
97
98
Fizz
Buzz
101
Fizz
103
104
FizzBuzz
106
107
Fizz
109
Buzz
Fizz
112
113
Fizz
Buzz
116
Fizz
118
119
FizzBuzz
121
122
Fizz
124
Buzz
Fizz
127
128
Fizz
Buzz
131
Fizz
133
134
FizzBuzz
136
137
Fizz
139
Buzz
Fizz
142
143
Fizz
Buzz
146
Fizz
148
149
FizzBuzz
151
152
Fizz
154
Buzz
Fizz
157
158
Fizz
Buzz
161
Fizz
163
164
FizzBuzz
166
167
Fizz
169
Buzz
Fizz
172
173
Fizz
Buzz
176
Fizz
178
179
FizzBuzz
181
182
Fizz
184
Buzz
Fizz
187
188
Fizz
Buzz
191
Fizz
193
194
FizzBuzz
196
197
Fizz
199


In [1]:
def affichage() :
    print "Hello, World !"

In [2]:
affichage()

Hello, World !


In [39]:
def factorielle(n=6):
    p=1
    for i in range (1,n+1):
        p*=i
    return p

factorielle()

720

In [15]:
def triangle(n):
    tri = ""
    for i in range(n):
        tri += "*"
        print tri

triangle(10)

*
**
***
****
*****
******
*******
********
*********
**********


In [21]:
liste_random = np.random.randint(0, high=10, size=20).tolist()
liste_finale = []
for i in liste_random :
    if i > 3 :
        liste_finale.append(i)
print 'liste random',liste_random
print 'liste finale',liste_finale

liste random [6, 9, 3, 8, 0, 9, 8, 3, 4, 5, 3, 4, 5, 9, 4, 5, 0, 8, 3, 0]
liste finale [6, 9, 8, 9, 8, 4, 5, 4, 5, 9, 4, 5, 8]


In [26]:
liste_finale2 = [x for x in liste_random if x>3]
liste_finale2

[6, 9, 8, 9, 8, 4, 5, 4, 5, 9, 4, 5, 8]

### Quicksort

In [18]:
import numpy as np

def quicksort(l) :
    if len(l) <=1 :
        return l
    else :
        pivot = l[-1]
        l.pop()
        lg=[]
        ll=[]
        for i in l :
            if i <= pivot :
                ll.append(i)
            else :
                lg.append(i)
    return quicksort(ll)+[pivot]+quicksort(lg)

liste_random = np.random.randint(0, high=100, size=20).tolist()
liste_triee = quicksort(liste_random)
print "liste random :",liste_random
print "\nliste triée :",liste_triee   

liste random : [73, 58, 64, 28, 41, 71, 87, 46, 57, 72, 96, 73, 58, 22, 66, 0, 76, 28, 70]

liste triée : [0, 9, 22, 28, 28, 41, 46, 57, 58, 58, 64, 66, 70, 71, 72, 73, 73, 76, 87, 96]


### paramètres fonctions

In [6]:
def creer_fiche(nom,prenom, *reste):
    chaine = "nom : "+nom+"\nprenom : " + prenom
    if reste :
        chaine +="\ninformations complementaires : "
    for i in reste :
        chaine+=i+" " 
    return chaine

informations = creer_fiche("Dupond", "Paul")
print informations +"\n"
informations2 = creer_fiche("Dupond", "Paul",'10 rue des lilas','75001', "Paris")
print informations2

nom : Dupond
prenom : Paul

nom : Dupond
prenom : Paul
informations complementaires : 10 rue des lilas 75001 Paris 


nom : Dupond
prenom : Paul
informations complementaires : 10 rue des lilas 75001 Paris 


In [59]:
adresse = ["10 rue des lilas", "75001", "Paris"]
informations = creer_fiche("Dupond", "Paul", *adresse)
print informations

nom : Dupond
prenom : Paul
informations complementaires : 10 rue des lilas 75001 Paris 


In [62]:
tuple_vide = ()
print tuple_vide, type(tuple_vide)
tuple_un_element = (2,)  #attention la virgule est obligatoire pour un unique element
print tuple_un_element
tuple_mutliples_elements = (1,2,3)
print tuple_mutliples_elements

() <type 'tuple'>
(2,)
(1, 2, 3)


### dictionnaires

In [63]:
dico_vide = {}
print dico_vide , type(dico_vide)

{} <type 'dict'>


In [135]:
carnet_contact ={"nom1" : "Dupond", "prenom1":"Paul", "nom2":"Dubois", "prenom2" : "Charles"}
print carnet_contact
#del carnet_contact["nom2"]
#del carnet_contact["prenom2"]
carnet_contact

{'nom2': 'Dubois', 'nom1': 'Dupond', 'prenom2': 'Charles', 'prenom1': 'Paul'}


{'nom2': 'Dubois', 'nom1': 'Dupond', 'prenom2': 'Charles', 'prenom1': 'Paul'}

In [123]:
carnet_contact["nom3"] =  "Martin"
carnet_contact["prenom3"] = "Pierre"
carnet_contact

{'nom2': 'Dubois', 'nom3': 'Martin', 'nom1': 'Dupond', 'prenom2': 'Charles', 'prenom3': 'Pierre', 'prenom1': 'Paul'}

In [140]:
print carnet_contact
for i,j in carnet_contact.items():
    print i,j

{'nom2': 'Dubois', 'nom1': 'Dupond', 'prenom2': 'Charles', 'prenom1': 'Paul'}
nom2 Dubois
nom1 Dupond
prenom2 Charles
prenom1 Paul


In [121]:
dico = {"un" : 1, "deux":2, "trois": 3}
dico.viewitems()

dict_items([('un', 1), ('trois', 3), ('deux', 2)])

### copies de variable en python !!!

In [76]:
liste1 = [0,1,2]
liste2 = liste1
print liste2
liste1.append(3)
print liste2

[0, 1, 2]
[0, 1, 2, 3]


In [82]:
liste1 = [0,1,2]
liste2 = list(liste1) #technique 1
liste3 = liste1[:]    #technique 2

In [228]:
dico_note = {"lloyd":lloyd, "alice":alice, 'tyler': tyler}

In [246]:
bob = {
  "nom": "Bob",
  "devoir": [90.0,97.0,75.0,92.0],
  "qcm": [88.0,40.0,94.0],
  "exam": [75.0,90.0]
}
alice = {
  "prenom": "Alice",
  "devoirs": [100.0, 92.0, 98.0, 100.0],
  "qcm": [82.0, 83.0, 91.0],
  "exam": [89.0, 97.0]
}
tyler = {
  "prenom": "Carol",
  "devoir": [0.0, 87.0, 75.0, 22.0],
  "qcm": [0.0, 75.0, 78.0],
  "exam": [100.0, 100.0]
}

dico_note = {"bob" :lloyd, "alice":alice, 'carol' : tyler}

#moyenne des 3
for i, j in dico_note.items() :
    for j in dico_note[i].keys():
        if type(dico_note[i][j]) is list :
            dico_note[i]['moyenne_'+j] = np.mean(dico_note[i][j])
            
for i in dico_note.keys() :
    dico_note[i]['moyenne_generale'] = 0
    for j in dico_note[i].keys() :
        if j.startswith('moy') and j != "moyenne_generale" :
            dico_note[i]['moyenne_generale'] += dico_note[i][j]
    dico_note[i]['moyenne_generale'] = float("{0:.1f}".format(dico_note[i]["moyenne_generale"]/3))
for i in dico_note.keys() :
    print i, dico_note[i]["moyenne_generale"]

carol 65.7
bob 81.7
alice 91.9


In [248]:
l=range(10)
l

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [249]:
for i,item in enumerate(l):
    print i,item

0 0
1 1
2 2
3 3
4 4
5 5
6 6
7 7
8 8
9 9


In [3]:
a = 3
def mafonction(a):
    b=2
    a += b
    print "a:",a,"b:",b
    
mafonction(a)
print "a:",a,"b:", b

 a: 5 b: 2
a: 3 b:

NameError: name 'b' is not defined

In [7]:
import math

In [20]:
import math as m

In [21]:
print math.cos(-2*math.pi)
print m.cos(2*math.pi)

1.0
1.0


In [15]:
print dir(math)

['__doc__', '__name__', '__package__', 'acos', 'acosh', 'asin', 'asinh', 'atan', 'atan2', 'atanh', 'ceil', 'copysign', 'cos', 'cosh', 'degrees', 'e', 'erf', 'erfc', 'exp', 'expm1', 'fabs', 'factorial', 'floor', 'fmod', 'frexp', 'fsum', 'gamma', 'hypot', 'isinf', 'isnan', 'ldexp', 'lgamma', 'log', 'log10', 'log1p', 'modf', 'pi', 'pow', 'radians', 'sin', 'sinh', 'sqrt', 'tan', 'tanh', 'trunc']


In [22]:
import xgboost

ImportError: No module named xgboost

In [24]:
l = [1, 0, None, [], True]
l = [a for a in l if a ]
l

[1, True]

In [31]:
l =[a**2 for a in range(10) if a%2 == 0]
l

[0, 4, 16, 36, 64]

In [29]:
l=[]
for i in range(10) :
    a = i**2
    l.append(a)
l

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

In [7]:
matrix = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
[[el - 1 for el in row] for row in matrix]

[[0, 1, 2], [3, 4, 5], [6, 7, 8]]

In [9]:
def fonction_avec_exception(param):
    if param not in (1, 2, 3):
        raise ValueError("param ne peut etre egal qu'a 1, 2 ou 3")
    else :
        print param
fonction_avec_exception(4)

ValueError: param ne peut etre egal qu'a 1, 2 ou 3

In [27]:
i="c"
l = ["a","b","c"]
try:
    resultat = l[i]
except IndexError :
    print "i est trop grand !"
    resultat = None
except NameError :
    print "o n'est pas définit"
    resultat = None
except TypeError :
    print "i doit être un entier"
    resultat = None

i doit être un entier


In [16]:

personnages = ['iron', 'super', 'bat', 'clepto']
try:
    resultat = personnages[i]
# i est plus grand que la taille du tableau
except:
    print "unexpected indent"
    resultat = None
        

NameError: name 'o' is not defined

In [15]:
try:
    numerateur = float(input("numerateur : "))
    denominateur = float(input("denominateur : "))
    division = numerateur*1.0/denominateur
    arrondi = round(division,2)
    print division
    print arrondi
except (ValueError, NameError, SyntaxError) :
    print 'le numérateur et le dénominateur doivent être des flottants'
except ZeroDivisionError :
    print 'le dénominateur ne doit pas être nul'

numerateur : 7 
denominateur : 8
0.875
0.88


In [18]:
data= np.random.randn(1000)
cut = pd.qcut(data,4)
cut

[(0.0127, 0.739], (-0.675, 0.0127], (0.0127, 0.739], (0.0127, 0.739], (-0.675, 0.0127], ..., (0.0127, 0.739], (0.739, 3.568], (0.739, 3.568], (0.0127, 0.739], (-0.675, 0.0127]]
Length: 1000
Categories (4, object): [[-3.401, -0.675] < (-0.675, 0.0127] < (0.0127, 0.739] < (0.739, 3.568]]

In [20]:
help(id)

Help on built-in function id in module __builtin__:

id(...)
    id(object) -> integer
    
    Return the identity of an object.  This is guaranteed to be unique among
    simultaneously existing objects.  (Hint: it's the object's memory address.)



In [109]:
y=np.array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]])
y.shape

(3L, 8L)

In [45]:
np.insert(a, 1,8)

array([0, 8, 1, 2])

In [50]:
np.add(a,[5,6,7])

array([5, 7, 9])

In [147]:
a = np.array([[1,2],[3,4]])
b = np.array([1,2,3])
c = b = np.array([[1],[2],[3]])
print a.shape, b.shape, c.shape
print a
print b
print c
a.reshape(1,1,4)

(2L, 2L) (3L, 1L) (3L, 1L)
[[1 2]
 [3 4]]
[[1]
 [2]
 [3]]
[[1]
 [2]
 [3]]


array([[[1, 2, 3, 4]]])

In [150]:
b = np.arange(9)
b.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])